### ISSUE TITLE
Unify existing gentropy DAGs

### ISSUE THREAD

**Issue by project-defiant** [opentargets/orchestration#27]
## Objective

As a developer I want to **unify the way we create** DAGs and define the topology for existing genetic data sources processing steps. 

### Context

Genetic DAGs use the `gentropy steps` to perform specific actions releated to genetic data source processing. Datasources ingested by genetic dags consist of:
- finngen GWAS fine mapping results
- finngen ukbppp meta analysis results
- ukbppp eur QTL results
- gnomad variants
- gnomad ld_matrix
- gwas_catalog top associations
- gwas_catalog summary_statistics
- eqtl_catalogue QTL fine mapping results

Most of the sources above generate from 1 to 2 dags (except gwas_catalog, in which the DAGs unify both sources before processing in continuous manner).

All of the genetic_dags (except gwas_catalog releated ones) have specific life cycle coupled with datasource release process that is not handled by Open Targets, so they are not updated during each data release, rather only when the datasource has an update itself (for example bump of finngen GWAS release from r10 to r11).

The entire business logic to full genetic processing is defined in three places:
- [gentropy](https://github.com/opentargets/gentropy/tree/dev/src/gentropy) - contains business of each of the DAGs tasks within the `gentropy step classes` that are exposed by hydra command line interface. 
- [hydra structured configuration](https://github.com/opentargets/orchestration/tree/dev/config) - contains all parameters that define how each of the tasks should be called inside the DAGs
- [dags](https://github.com/opentargets/orchestration/tree/dev/src/ot_orchestration/dags) - contains topologies of each specific datasource processing and overwrites for the hydra configuration

> [!IMPORTANT]
> Each of the gentropy steps have to be run on `spark cluster`, currently the dags allow for invoking the steps inside the dataproc cluster, by copying entire hydra configuration to the dataproc cluster, while overwriting some of the parameters directly inside the DAG.

While this process is easy to follow when developing new steps, understanding entire process requires heavy amount of following nested configuration that can be defined in multiple locations (gentropy config.py, structured config, overwrites in the DAGs). 

The entire process is also error prone to dependency overwrite issue, as the cluster configuration and gentropy version are decoupled from the DAGs and are pre-requisite run by `make build` command inside the gentropy itself. This way the data generated by the DAGs does not contain any relevant information on which version of gentropy was used to generate it.

## Tasks

- [x] The DAGs topology should be inferred directly from the dag configuration, as it is done inside the `gentropy_etl.py` dag 
- [ ] The DAGs should not overwrite the parameters introduced by confuration layer
- [ ] For each DAG , it's step configurations should be extracted from the overall hydra configuration and wrapped around a single config file - this will streamline the readability of the dags.
- [ ] Allow for specifying cluster configurations (startup script, specific gentropy version and dependency installer) via the dag configuration.

## Next steps
- [ ] gwas_catalog dags should be deprecated, instead the `gwas_catalog_pipeline` dag should be promoted as a production ready dag
